# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(verbose_name='企    业    编    号')),
                ('company_src_name', models.CharField(max_length=50, verbose_name='应急响应中心')),
                ('company_src_www', models.URLField(verbose_name='应急中心地址')),
                ('company_name', models.CharField(max_length=50, verbose_name='企业名称')),
                ('company_www', models.URLField(verbose_name='官网地址')),
                ('company_ioc', models.URLField(null=True, verbose_name='企业图标')),
                ('company_starttime', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('company_updatetime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='应用名称')),
                ('port', models.CharField(max_length=30, verbose_name='开放端口')),
                ('product', models.CharField(max_length=30, verbose_name='对应服务')),
                ('version', models.CharField(max_length=30, verbose_name='应用版本')),
                ('cpe', models.CharField(max_length=30, verbose_name='终端说明')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50, null=True, verbose_name='服务器名称')),
                ('server_ip', models.GenericIPAddressField(verbose_name='服务器IP')),
                ('server_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_in_company', to='SRCCompany.CompanyInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain_name', models.CharField(max_length=50, null=True, verbose_name='子域名名称')),
                ('subdomain_www', models.URLField(verbose_name='子域名地址')),
                ('subdomain_starttime', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('subdomain_updatetime', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('subdomain_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_in_company', to='SRCCompany.CompanyInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Webinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_front', models.CharField(max_length=30, null=True, verbose_name='前端语言')),
                ('web_language', models.CharField(max_length=30, null=True, verbose_name='开发语言')),
                ('web_framework', models.CharField(max_length=30, null=True, verbose_name='开发框架')),
                ('web_template', models.CharField(max_length=30, null=True, verbose_name='网站模板')),
                ('web_container', models.CharField(max_length=30, null=True, verbose_name='WEB容器')),
                ('web_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_in_subdomain', to='SRCCompany.Subdomain')),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='port_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_in_server', to='SRCCompany.Server'),
        ),
    ]
