# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCCompany', '0002_subdomain_subdomain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='subdomain_id',
            field=models.CharField(max_length=50, verbose_name='子域名编号'),
        ),
    ]
