# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRCCompany', '0004_auto_20171209_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_subdomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_in_subdomain', to='SRCCompany.Subdomain'),
        ),
    ]
