# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRCCompany', '0005_auto_20171209_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='web_url',
            field=models.URLField(null=True, verbose_name='网页链接'),
        ),
        migrations.AlterField(
            model_name='plug',
            name='plug_subdomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plug_in_webinfo', to='SRCCompany.Webinfo'),
        ),
        migrations.AlterField(
            model_name='plug',
            name='plug_version',
            field=models.CharField(max_length=30, null=True, verbose_name='组件版本'),
        ),
        migrations.AlterField(
            model_name='port',
            name='cpe',
            field=models.CharField(max_length=30, null=True, verbose_name='终端说明'),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='应用名称'),
        ),
        migrations.AlterField(
            model_name='port',
            name='product',
            field=models.CharField(max_length=30, null=True, verbose_name='对应服务'),
        ),
        migrations.AlterField(
            model_name='port',
            name='version',
            field=models.CharField(max_length=30, null=True, verbose_name='应用版本'),
        ),
    ]
