# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SRCCompany', '0006_auto_20171210_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_starttime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='server_updatetime',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
