# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCCompany', '0008_auto_20171210_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='web_id',
            field=models.CharField(max_length=50, null=True, verbose_name='网页编号'),
        ),
    ]
