# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCCompany', '0009_webinfo_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='web_id',
            field=models.IntegerField(verbose_name='网页编号'),
        ),
    ]
