# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRCCompany', '0011_auto_20171210_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plug',
            name='plug_webinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plug_in_webinfo', to='SRCCompany.Webinfo', verbose_name='网页关联'),
        ),
        migrations.AlterField(
            model_name='port',
            name='port_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_in_server', to='SRCCompany.Server', verbose_name='服务器关联'),
        ),
        migrations.AlterField(
            model_name='webinfo',
            name='web_id',
            field=models.CharField(max_length=50, verbose_name='网页编号'),
        ),
    ]
