# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRCCompany', '0013_auto_20171211_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_os',
            field=models.CharField(max_length=30, null=True, verbose_name='操作系统'),
        ),
    ]
